DROP TABLE IF EXISTS user;

CREATE TABLE user
(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT, 
	username VARCHAR(45) NOT NULL UNIQUE, 
	password VARCHAR(45) NOT NULL, 
	fname VARCHAR(45) NOT NULL, 
	lname VARCHAR(45) NOT NULL,
	PRIMARY KEY (id) 
);
